# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_sync_buf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_sync_buf.proto',
  package='FileSyncDemo',
  serialized_pb='\n\x13\x66ile_sync_buf.proto\x12\x0c\x46ileSyncDemo\"\xd6\x01\n\x08\x46ileSync\x12\n\n\x02to\x18\x01 \x02(\t\x12\x0c\n\x04\x66rom\x18\x02 \x02(\t\x12=\n\x08\x64\x61taType\x18\x03 \x02(\x0e\x32#.FileSyncDemo.FileSync.FileSyncType:\x06UPDATE\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x02(\x05\"P\n\x0c\x46ileSyncType\x12\n\n\x06UPDATE\x10\x00\x12\r\n\tSUBSCRIBE\x10\x01\x12\x0f\n\x0bUNSUBSCRIBE\x10\x02\x12\t\n\x05HELLO\x10\x03\x12\t\n\x05OTHER\x10\x04')



_FILESYNC_FILESYNCTYPE = _descriptor.EnumDescriptor(
  name='FileSyncType',
  full_name='FileSyncDemo.FileSync.FileSyncType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELLO', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=172,
  serialized_end=252,
)


_FILESYNC = _descriptor.Descriptor(
  name='FileSync',
  full_name='FileSyncDemo.FileSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='FileSyncDemo.FileSync.to', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from', full_name='FileSyncDemo.FileSync.from', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='FileSyncDemo.FileSync.dataType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='FileSyncDemo.FileSync.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FileSyncDemo.FileSync.timestamp', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILESYNC_FILESYNCTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=252,
)

_FILESYNC.fields_by_name['dataType'].enum_type = _FILESYNC_FILESYNCTYPE
_FILESYNC_FILESYNCTYPE.containing_type = _FILESYNC;
DESCRIPTOR.message_types_by_name['FileSync'] = _FILESYNC

class FileSync(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILESYNC

  # @@protoc_insertion_point(class_scope:FileSyncDemo.FileSync)


# @@protoc_insertion_point(module_scope)
