# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageBuf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messageBuf.proto',
  package='SensorDemo',
  serialized_pb='\n\x10messageBuf.proto\x12\nSensorDemo\"\xc0\x05\n\x07Message\x12:\n\x04type\x18\x01 \x02(\x0e\x32\x1f.SensorDemo.Message.MessageType:\x0bSENSOR_DATA\x12\x42\n\x0c\x65ncAlgorithm\x18\x02 \x02(\x0e\x32\'.SensorDemo.Message.MessageEncAlgorithm:\x03\x41\x45S\x12G\n\x0cibeAlgorithm\x18\x03 \x02(\x0e\x32\'.SensorDemo.Message.MessageIbeAlgorithm:\x08WATERS09\x12\x45\n\x0cibsAlgorithm\x18\x04 \x02(\x0e\x32\'.SensorDemo.Message.MessageIbsAlgorithm:\x06WATERS\x12$\n\x1cidentityBasedMasterPublicKey\x18\x05 \x02(\t\x12-\n%identityBasedSignatureMasterPublicKey\x18\x06 \x01(\t\x12!\n\x19identityBasedEncryptedKey\x18\x07 \x01(\t\x12\x18\n\x10\x65ncryptedMessage\x18\x08 \x01(\t\x12\x13\n\x0b\x65ncryptedPK\x18\t \x01(\t\x12\x14\n\x0c\x65ncryptedSPK\x18\n \x01(\t\x12\r\n\x05nonce\x18\x0b \x02(\t\x12\x11\n\ttimestamp\x18\x0c \x02(\x05\"3\n\x0bMessageType\x12\x08\n\x04INIT\x10\x00\x12\x0f\n\x0bSENSOR_DATA\x10\x01\x12\t\n\x05OTHER\x10\x02\";\n\x13MessageEncAlgorithm\x12\x07\n\x03\x41\x45S\x10\x00\x12\x07\n\x03\x44\x45S\x10\x01\x12\x08\n\x04\x44\x45S3\x10\x02\x12\x08\n\x04NONE\x10\x03\"1\n\x13MessageIbeAlgorithm\x12\x0c\n\x08WATERS05\x10\x00\x12\x0c\n\x08WATERS09\x10\x01\"!\n\x13MessageIbsAlgorithm\x12\n\n\x06WATERS\x10\x00')



_MESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='SensorDemo.Message.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_DATA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=539,
  serialized_end=590,
)

_MESSAGE_MESSAGEENCALGORITHM = _descriptor.EnumDescriptor(
  name='MessageEncAlgorithm',
  full_name='SensorDemo.Message.MessageEncAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DES', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DES3', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=592,
  serialized_end=651,
)

_MESSAGE_MESSAGEIBEALGORITHM = _descriptor.EnumDescriptor(
  name='MessageIbeAlgorithm',
  full_name='SensorDemo.Message.MessageIbeAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WATERS05', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WATERS09', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=653,
  serialized_end=702,
)

_MESSAGE_MESSAGEIBSALGORITHM = _descriptor.EnumDescriptor(
  name='MessageIbsAlgorithm',
  full_name='SensorDemo.Message.MessageIbsAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WATERS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=704,
  serialized_end=737,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='SensorDemo.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SensorDemo.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encAlgorithm', full_name='SensorDemo.Message.encAlgorithm', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ibeAlgorithm', full_name='SensorDemo.Message.ibeAlgorithm', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ibsAlgorithm', full_name='SensorDemo.Message.ibsAlgorithm', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identityBasedMasterPublicKey', full_name='SensorDemo.Message.identityBasedMasterPublicKey', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identityBasedSignatureMasterPublicKey', full_name='SensorDemo.Message.identityBasedSignatureMasterPublicKey', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identityBasedEncryptedKey', full_name='SensorDemo.Message.identityBasedEncryptedKey', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptedMessage', full_name='SensorDemo.Message.encryptedMessage', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptedPK', full_name='SensorDemo.Message.encryptedPK', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptedSPK', full_name='SensorDemo.Message.encryptedSPK', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='SensorDemo.Message.nonce', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SensorDemo.Message.timestamp', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_MESSAGETYPE,
    _MESSAGE_MESSAGEENCALGORITHM,
    _MESSAGE_MESSAGEIBEALGORITHM,
    _MESSAGE_MESSAGEIBSALGORITHM,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=737,
)

_MESSAGE.fields_by_name['type'].enum_type = _MESSAGE_MESSAGETYPE
_MESSAGE.fields_by_name['encAlgorithm'].enum_type = _MESSAGE_MESSAGEENCALGORITHM
_MESSAGE.fields_by_name['ibeAlgorithm'].enum_type = _MESSAGE_MESSAGEIBEALGORITHM
_MESSAGE.fields_by_name['ibsAlgorithm'].enum_type = _MESSAGE_MESSAGEIBSALGORITHM
_MESSAGE_MESSAGETYPE.containing_type = _MESSAGE;
_MESSAGE_MESSAGEENCALGORITHM.containing_type = _MESSAGE;
_MESSAGE_MESSAGEIBEALGORITHM.containing_type = _MESSAGE;
_MESSAGE_MESSAGEIBSALGORITHM.containing_type = _MESSAGE;
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

class Message(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGE

  # @@protoc_insertion_point(class_scope:SensorDemo.Message)


# @@protoc_insertion_point(module_scope)
